name: Required Reviews
on:
  pull_request: {}
  pull_request_review: {}
jobs:
  required-reviews:
    name: Required Reviews
    runs-on: ubuntu-latest
    steps:
      - name: required-reviewers
        uses: rahul2123/required-reviews
        with:
          github-token: ${{ secrets.PR_TOKEN }}
          # Optional: post a review on the PR instead of failing the task when requirements haven't been satisfied
          # post-review: true