name: Check Approvals

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-approvals:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Approvals
        run: |
          PR_NUMBER=$(echo "${{ github.event.number }}")
          REPO_OWNER=$(echo "${{ github.repository_owner }}")
          REPO_NAME=$(echo "${{ github.repository }}")
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          
          APPROVALS=$(curl -s -H "Authorization: Bearer $TOKEN" \
                       -H "Accept: application/vnd.github.v3+json" \
                       "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER/reviews" | \
                       jq '.[] | select(.state == "APPROVED")')

          if [ -z "$APPROVALS" ]; then
            echo "At least one approval is required."
            exit 1
          else
            echo "PR has at least one approval."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}
