on: pull_request_review
name: Multi Approved Example Job
jobs:
  onApprovedSubmit:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - uses: sakhnovict/multi-approved-event-action@1.0.9
      id: approved
      with:
        approvalsCount: 2
      env:
        GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}
    - run: echo "Approved 2 times."
      if: steps.approved.outputs.isApproved == 'true'